/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

/*
find single in s+t
*/

class Solution {
public:
    char findTheDifference01(string s, string t) {
        int ss[26] = {0};
        int i,j;
        for(i = 0; i < t.size(); ++i)
        {
            if(i < s.size()) ss[int(s[i]-'a')]++;
            ss[int(t[i]-'a')]--;
        }
        for(j = 0; j < 25; ++j)
        {
            if(ss[j]<0) break;
        }
        return j+'a';
    }
    
    
    char findTheDifference(string s, string t) {
        int bit = '0';
        for(int i = 0; i < t.size(); ++i)
        {
            if(i < s.size()) bit = bit ^ s[i];
            bit = bit ^ t[i];
        }
        return bit ^ '0';
    }
};